version: '3'

services:
  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/pages:/app/pages
      - ./client/src:/app/src
      - ./client/dist:/app/dist
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/app/src
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/gear?connect_timeout=300
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
volumes:
  db_data: