version: '3'

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app/pages
      - ./src:/app/src
      - ./dist:/app/dist
    environment:
      - DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/gear
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    # restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
volumes:
  db_data: